services:
  - type: web
    name: stylesync-backend-glao
env: python
    pythonVersion: "3.11"
buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir --force-reinstall
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
