"""initial models

Revision ID: 3ef507ed535b
Revises: 
Create Date: 2026-04-09 00:50:16.835460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef507ed535b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('html_snapshot', sa.String(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_sites_id'), 'scraped_sites', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_sites_url'), 'scraped_sites', ['url'], unique=True)
    op.create_table('design_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('typography', sa.JSON(), nullable=True),
    sa.Column('spacing', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['scraped_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_tokens_id'), 'design_tokens', ['id'], unique=False)
    op.create_table('locked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('token_key', sa.String(), nullable=True),
    sa.Column('locked_value', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['design_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locked_tokens_id'), 'locked_tokens', ['id'], unique=False)
    op.create_table('version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['design_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_history_id'), 'version_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_history_id'), table_name='version_history')
    op.drop_table('version_history')
    op.drop_index(op.f('ix_locked_tokens_id'), table_name='locked_tokens')
    op.drop_table('locked_tokens')
    op.drop_index(op.f('ix_design_tokens_id'), table_name='design_tokens')
    op.drop_table('design_tokens')
    op.drop_index(op.f('ix_scraped_sites_url'), table_name='scraped_sites')
    op.drop_index(op.f('ix_scraped_sites_id'), table_name='scraped_sites')
    op.drop_table('scraped_sites')
    # ### end Alembic commands ###
